sudo: required
services:
  - docker

before_install:
  - docker build -t swaraj4798/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true swaraj4798/react-test npm test -- --coverage

after_success:
  - docker build -t logan4798/multi-client ./client
  - docker build -t logan4798/multi-nginx ./nginx
  - docker build -t logan4798/multi-server ./server
  - docker build -t logan4798/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push logan4798/multi-client
  - docker push logan4798/multi-nginx
  - docker push logan4798/multi-server
  - docker push logan4798/multi-worker  